M = 3000; 
sigA = [0.8:0.0001:0.9979,1.0001:0.0001:1.002];
N = size(sigA,2); 
dense = 0.2; 
A = sprand(M,N,dense,sigA);

k = 20;
target = 1;
outtol = 1e-8;
maxit = min(M,N);
maxdim = 30;
mindim = 3;
fixtol = 0;
inntol = 1e-4;
u0 = ones(M,1);
v0 = ones(N,1);

% Tests with matrices;
innprectol1 = 0.05;     innprectol2 = 0.01;
[Tp,Up,Vp,RELRESp,OUTITp,INNITp,INNITPERSTEPp,CPUTIMEp,FLAGp,PERCp] = ...
    ipjdsvd(A,k,target,'Tolerance',outtol,'MaxIterations',maxit,...
    'MaxSubspaceDimension',maxdim,'MinSubspaceDimension',mindim,...
    'SwitchingTolerance',fixtol,'InnerTolerance',inntol,...
    'LeftStartVector',u0,'RightStartVector',v0,...
    'InnerPreconditionTolerance1',innprectol1,...
    'InnerPreconditionTolerance2',innprectol2,'Display',1);
 
innprectol1 = 0;        innprectol2 = 0;
[To,Uo,Vo,RELRESo,OUTITo,INNITo,INNITPERSTEPo,CPUTIMEo,FLAGo,PERCo]=...
    ipjdsvd(A,k,target,'Tolerance',outtol,'MaxIterations',maxit,...
    'MaxSubspaceDimension',maxdim,'MinSubspaceDimension',mindim,...
    'SwitchingTolerance',fixtol,'InnerTolerance',inntol,...
    'LeftStartVector',u0,'RightStartVector',v0,...
    'InnerPreconditionTolerance1',innprectol1,...
    'InnerPreconditionTolerance2',innprectol2,'Display',1);

% Tests with function handles;
afun = MatrixFunction(A);
innprectol1 = 0.05;     innprectol2 = 0.01;
[Tp,Up,Vp,RELRESp,OUTITp,INNITp,INNITPERSTEPp,CPUTIMEp,FLAGp,PERCp]=...
    ipjdsvd(afun,[M N],k,target,'Tolerance',outtol,'MaxIterations',maxit,...
    'MaxSubspaceDimension',maxdim,'MinSubspaceDimension',mindim,...
    'SwitchingTolerance',fixtol,'InnerTolerance',inntol,...
    'LeftStartVector',u0,'RightStartVector',v0,...
    'InnerPreconditionTolerance1',innprectol1,...
    'InnerPreconditionTolerance2',innprectol2,'Display',displayornot);

innprectol1 = 0;        innprectol2 = 0;
[To,Uo,Vo,RELRESo,OUTITo,INNITo,INNITPERSTEPo,CPUTIMEo,FLAGo,PERCo]=...
    ipjdsvd(afun,[M N],k,target,'Tolerance',outtol,'MaxIterations',maxit,...
    'MaxSubspaceDimension',maxdim,'MinSubspaceDimension',mindim,...
    'SwitchingTolerance',fixtol,'InnerTolerance',inntol,...
    'LeftStartVector',u0,'RightStartVector',v0,...
    'InnerPreconditionTolerance1',innprectol1,...
    'InnerPreconditionTolerance2',innprectol2,'Display',displayornot);


% MatrixFunction turns a matrix to a function handle
% For experimental purpose only
function varargout = MatrixFunction(C)
% Creat the function handle with a given matrix C.

varargout{1} = @matrixfun;
    function y = matrixfun(x,transpornot)
        if strcmp(transpornot,'notransp')
            y = C*x;
        elseif strcmp(transpornot,'transp')
            y = C'*x;
        else
            error('wrong input for transpornot');
        end
    end
end